spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rafacar_db
    username: rafacar
    password: rafacar123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  application:
    name: rafacar-backend
  flyway:
    out-of-order: true


server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger
